### ISSUE TITLE
Strange entry in my Devlog history

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#1121]
I found this when I scrolled down in my DevLog Dashboard page of my game Star Story
![image](https://user-images.githubusercontent.com/11202073/38776860-23723f12-409e-11e8-9707-205262663df5.png)

This game has always been a one-man show, so the only one who ever wrote devlogs for it was me, so deleted collaborator accounts should not be possible.

**Comment by hworld** [comment]
All of this should be fixed?

**Comment by Tricky1975** [comment]
![image](https://user-images.githubusercontent.com/11202073/39690550-cdc46876-51da-11e8-83f8-5941e7c0b7cc.png)

Taken from my sixty-three fires of Lung... :-/
And when checking my Star Story, where I discovered this issue... There are less of those then there used to be, but they are still present and still in big numbers.

**Comment by Tricky1975** [comment]
Supplement: Oh, further investigation shows that my Star Story is still as bad as it was when it comes to this... 🤔
