### ISSUE TITLE
Trouble with screenshots

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/issue-tracker#673]
![image](https://cloud.githubusercontent.com/assets/11202073/15100371/16678058-1570-11e6-80b1-161668d6ca54.png)

Above is just a random game. Many thumbnails are just black and many magnified versions turn up as a broken picture. I've seen this with many games already and it appears not to be just me since there's also a complaint about this one on the forums.

**Comment by Tricky1975** [comment]
It seems the achievements suffer from the same issue:
![image](https://cloud.githubusercontent.com/assets/11202073/15100408/0587fbfe-1571-11e6-8417-e1e6c74a02d1.png)

**Comment by hworld** [comment]
Is it fixed by any chance?

**Comment by Tricky1975** [comment]
I shall look into this, please gimme some time, as this happens pretty randomly, I cannot just deem it fixed by one or two looks.
(at a few moments I even saw this affect some avatars, and them being on gravatar was very odd for me).

There are also forum complaints on this one, so maybe I can ask in the specific thread if other people still see this happening.

**Comment by Tricky1975** [comment]
In the past 3 days I've taken an extra look into this to see if even 1 image would not show, and I was unable to replicate this. I guess that means this is fixed now???

**Comment by Tricky1975** [comment]
Correction, it still happened to me on my trophy setting for my game Star Story, so I guess the bug is not fixed.

**Comment by Tricky1975** [comment]
The last month I did not encounter this anymore, so I guess it's safe to deem this issue fixed or solved, or whatever. I shall bring this up again, if it occurs again on a large scale like this.
